### ISSUE TITLE
Setting custom properties

### ISSUE THREAD

**Issue by NickYoung-PanoramicData** [skarpdev/dotnetcore-hubspot-client#105]
Hello,
Is there currently an implementation to allow the setting of custom properties for contacts? If so how is it done?

**Comment by nover** [comment]
Hi there,

yes there is - and I believe it's covered in the readme:
https://github.com/skarpdev/dotnetcore-hubspot-client#contact

**Comment by NickYoung-PanoramicData** [comment]
Thats my mistake, I did not see that. Thank you for the help
