### ISSUE TITLE
Thread Exits with a status code of zero when calling  GetByEmailAsync<ContactHubSpotEntity>

### ISSUE THREAD

**Issue by rholsman** [skarpdev/dotnetcore-hubspot-client#17]
Here is a sample code snippet; bear in mind i have been adding try catches as an attempt to work around the issue. 

```
ContactHubSpotEntity hubspotContact = null;
var hubspotClient = new HubSpotContactClient(ConfigurationManager.AppSettings["HubSpotApiKey"]);
try
{
    hubspotContact = await hubspotClient.GetByEmailAsync<ContactHubSpotEntity>(viewModel.Email);
}
catch (Exception e)
{
    return false;
}
finally
{
    if (hubspotContact == null)
    {
        hubspotContact = new ContactHubSpotEntity()
        {
            Address = viewModel.AddressLine1 + " " + viewModel.AddressLine2,
            Company = viewModel.CompanyName,
            City = viewModel.City,
            Email = viewModel.Email,
            FirstName = viewModel.FirstName,
            Lastname = viewModel.LastName,
            Phone = viewModel.PhoneNumber, 
            State = viewModel.State,
            ZipCode = viewModel.ZipCode,
        };
        var success = await hubspotClient.CreateAsync<ContactHubSpotEntity>(hubspotContact);
    }
}     
return true; 
```

when the first await line is hit a 404 response is received from hubspot because the contact doesn't exist; but the response body is not empty and the object shape is not the same as the serializer is expecting.

```
{
status=error,
correlationId=42022ea2-0916-41d5-bfee-57edd3a23b60,
message=contact does not exist,
requestId=73bf33242099220cd1ab6e842e063d29
}
```
I believe the code in the SendRequestAsync method in the HubSpotBaseClient class needs some critiquing to handle the response when a 404 is returned with the error message.

**Comment by nover** [comment]
@rholsman Thanks for the bug report, I'll investigate it

**Comment by nover** [comment]
@rholsman Do you happen to have a stack-trace for the crash, becase we do already have a functional test with a 404 error 🤔

**Comment by rholsman** [comment]
`Evaluation requires a thread to run temporarily. Use the Watch window to perform the evaluation.
'task.Start()' threw an exception of type 'System.Threading.ThreadAbortException'
    Data: {System.Collections.ListDictionaryInternal}
    ExceptionState: null
    HResult: -2146233040
    HelpLink: null
    IPForWatsonBuckets: 0x71325459
    InnerException: null
    IsTransient: true
    Message: "Thread was being aborted."
    RemoteStackTrace: null
    Source: "mscorlib"
    StackTrace: "   at System.Diagnostics.Debugger.CustomNotification(ICustomDebuggerNotification data)\r\n   at System.Diagnostics.Debugger.NotifyOfCrossThreadDependencySlow()\r\n   at System.Diagnostics.Debugger.NotifyOfCrossThreadDependency()\r\n   at System.Threading.Tasks.Task.InternalWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)\r\n   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\r\n   at System.Threading.Tasks.Task`1.get_Result()"
    TargetSite: {Void CustomNotification(System.Diagnostics.ICustomDebuggerNotification)}
    WatsonBuckets: null
    _HResult: -2146233040
    _className: null
    _data: {System.Collections.ListDictionaryInternal}
    _dynamicMethods: null
    _exceptionMethod: {Void CustomNotification(System.Diagnostics.ICustomDebuggerNotification)}
    _exceptionMethodString: null
    _helpURL: null
    _innerException: null
    _ipForWatsonBuckets: 0x71325459
    _message: "Thread was being aborted."
    _remoteStackIndex: 0
    _remoteStackTraceString: null
    _safeSerializationManager: {System.Runtime.Serialization.SafeSerializationManager}
    _source: "mscorlib"
    _stackTrace: {sbyte[192]}
    _stackTraceString: null
    _watsonBuckets: null
    _xcode: -532462766
    _xptrs: 0x00000000
`

The error seems to only occur when attempt to resolve the Async operation with a .Result, await, or .Start() call for contacts who do not exist.

**Comment by nover** [comment]
@rholsman I have just created an integration test suite that tests `GetByEmailAsync` for contacts and it works on macOS with dotnet core sdk 2.0 (branch `bugfix/1-exit-code-contact-get-by-email-async`): 
https://github.com/skarpdev/dotnetcore-hubspot-client/commit/df80b7b054d55365a0293b0f32e00dbf82b4ec4d

Can you please try to check that branch out and run the test suite locally and report back with the exceptions?

It's connecting to the HubSpot demo API

**Comment by rholsman** [comment]
I think I was experiencing some sort of bug in the IDE itself restarting it has resolved the issue but I am experiencing some other issues with a null reference exception not moving up the stack correctly when calling create. Let me revisit this bug and I can report back at a later time.

**Comment by nover** [comment]
Okay, great 👍 

Please feel free to create a new issue with the null reference if you can confirm that it's actually a bug.

And that said, it is on the roadmap to add an integration test suite that actually talks with the HubSpot API to weed out any missed cases in the functional tests.

**Comment by rholsman** [comment]
Ok after much testing today I think there was an issue with either my IDE or the API endpoint at hubspot earlier when this ticket was created. 

This call seemed to throw some sort of runtime binding exception:
hubspotContact = await hubspotClient.GetByEmailAsync<ContactHubSpotEntity>(email);

that went away after a reboot of the machine; but I believe something with the json response body was causing an issue in an unexpected way.

I was successfully able to check for a user existing based on their email with this method later in the day; then was even able to create a user. Then after a few hours I can no longer create users using this call.
var success = await hubspotClient.CreateAsync<ContactHubSpotEntity>(hubspotContact); 
I run fiddler to capture requests regularly and caught this in the json response body.
validationResults 
{
error=PROPERTY_DOESNT_EXIST,
isValid=False,
message=Property "zipcode" does not exist,
name=zipcode
}

Upon reviewing the API documentation the correct field name is "zip" not "zipcode"; though this did work earlier in the day upon reviewing the contacts that were successfully created in our test portal. I did edit one of my capture requests to use "zip" in the json submit body and things did begin working again.

It's almost like different versions of the API exist? Maybe I am getting shifted between them or they are making changes to it live during the day?

**Comment by nover** [comment]
Thanks for the details @rholsman I'll try and squeeze in some time during the weekend to look into this.

**Comment by nover** [comment]
@rholsman I can confirm that what you have spotted with regards to the `zip` field holds true. I have added an integration test of create + get in commit f8233b64e64ee1f94b9c19337d15e0cb4cf3fcc0 and had to change the fieldname from `zipcode` to `zip` to get it to pass.

I have uploaded a pre-release package with version number `0.8.2-beta` - can you please confirm whether this one solves your issues?
https://www.nuget.org/packages/HubSpotClient/0.8.2-beta

Thanks in advance.

**Comment by rholsman** [comment]
Still getting a SystemNullReferenceException thrown at var success = await hubspotClient.CreateAsync<ContactHubSpotEntity>(hubspotContact);

`
try
            {
                var hubspotClient = new HubSpotContactClient(apiKey);
                hubspotContact = await hubspotClient.GetByEmailAsync<ContactHubSpotEntity>(email);
                if (hubspotContact == null)
                {
                    hubspotContact = new ContactHubSpotEntity()
                    {
                        FirstName = firstName ?? string.Empty,
                        Lastname = lastName ?? string.Empty,
                        Email = email ?? string.Empty,
                        Phone = phoneNumber ?? string.Empty,
                        Address = address ?? string.Empty,
                        Company = companyName ?? string.Empty,
                        City = city ?? string.Empty,
                        State = state ?? string.Empty,
                        ZipCode = zipCode ?? string.Empty,
                        Website = string.Empty
                    };
                    var success = await hubspotClient.CreateAsync<ContactHubSpotEntity>(hubspotContact);
                }
                log.Debug("Successfully created hubspot client.");
            }
            catch (Exception e)
            {
                log.Error(string.Format("There was an error adding the new customer {0} {1} at {2} to the Hubspot API.", firstName, lastName, companyName), e);
                throw e;
            }
`

**Comment by nover** [comment]
Is it possible for you to provide the stacktrace for the null reference exception?

**Comment by rholsman** [comment]
-		$exception	{"Object reference not set to an instance of an object."}	System.NullReferenceException
+		InnerException	null	System.Exception
		Message	"Object reference not set to an instance of an object."	string
		Source	"System.Web"	string
		StackTrace	"   at System.Web.ThreadContext.AssociateWithCurrentThread(Boolean setImpersonationContext)"	string

looks like the exception stack trace is not very helpful; seems to happen while during the async operation.

**Comment by nover** [comment]
Thanks, the trace does look a bit strange. Just for the reference, are you running in dotnet core or with dotnet 4.6.x full framework, and on which operating system?

Are you by any chance in a "corporate" context with proxies or any other funky network stuff?

**Comment by rholsman** [comment]
NullReferenceException was a thread safety issue in our code base. Thanks for the quick resolution on the actual bug!

**Comment by nover** [comment]
Great, I'll make sure to create a proper release with the fixes then. Glad you figured it out.

**Comment by nover** [comment]
Version `0.8.2` pushed to nuget.
