### ISSUE TITLE
ListAsync

### ISSUE THREAD

**Issue by twmmason** [skarpdev/dotnetcore-hubspot-client#21]
ListAsync for contacts currently seems to return a null list. Is this method still under development? Is there a way to implement this from outside the library?

**Comment by nover** [comment]
That's a bug, let me see if I can fix it quickly :)

**Comment by nover** [comment]
Will be available on nuget as version `0.8.3` any minute now.

**Comment by twmmason** [comment]
Thanks Nicklas.
