### ISSUE TITLE
Add interfaces to *HubSpotClient

### ISSUE THREAD

**Issue by roycornelissen** [skarpdev/dotnetcore-hubspot-client#43]
Thank you for this library! Works like a charm 👍 

I was wondering if you considered adding interfaces for all the `*HubSpotClient` classes so that they can be easily injected/mocked in unit tests? Or do you have another vision for mocking these?

**Comment by nover** [comment]
> Thank you for this library! Works like a charm 👍
Glad to hear that! 

That sounds like a great idea, I actually thought that I had decorated the member functions `virtual` to allow them to be overridden by a mocking framework, but I see that is not the case.

If you decide to post a PR with interfaces I will happily accept and merge it 👍

**Comment by roycornelissen** [comment]
See #44 :)

I had one doubt... do you think the `PathResolver()` methods belong on these interfaces? They seem relevant for the clients themselves but I don't see much use for them on the abstractions?

**Comment by nover** [comment]
@roycornelissen 

I think that the `PathResolver()` should _not_ be on the interface. You are right in your assessment that it is very important to the actual implementation of the client, but it has zero relevance on interface.

**Comment by roycornelissen** [comment]
@nover OK, will remove them from the interfaces

**Comment by roycornelissen** [comment]
@nover they're gone from the interfaces. I think they could best be made private in the clients, but this will break the public API.

**Comment by nover** [comment]
@roycornelissen thanks, it's merged, i'll get it released immediately.

That's a good suggestion, but the question is whether that breaking change is really going to break things for anyone.
