### ISSUE TITLE
New HubSpot API

### ISSUE THREAD

**Issue by roycornelissen** [skarpdev/dotnetcore-hubspot-client#48]
I also noticed that HubSpot has a new API, but it seems to be work in progress. Are there plans to migrate to this API? There seem to be some community questions/initiatives around generating OpenApi specs so that a client could be generated but I have no idea about the timeline.

So I guess my question is... how much should be invested in binding old `v1` or `v2` endpoints...?

As mentioned in #47, I do need to bind `Line Items` on a short term, so I'll attempt to add this based on the `v1` API.

**Comment by nover** [comment]
I noticed, but I decided not to dig into it at the time :)

If HubSpot could provide a definite timeline on the new API it would be easier to make the decision.
I guess if you need it now for a production application the time is well spent adding support for the `Line Items`.

**Comment by nover** [comment]
@roycornelissen I've opened up the new github feature `discussions` so I'm closing this issue in favor of continuing this as a discussion
