### ISSUE TITLE
Some bugs in Associations 

### ISSUE THREAD

**Issue by roycornelissen** [skarpdev/dotnetcore-hubspot-client#50]
I noticed some bugs in the `Associations` implementation. Working on a fix, will submit a PR ASAP.

- The methods on the `HubSpotAssociationsClient` all have a parameter for the definition ID, but they are never used since the entities also have a field for this. I think this should be removed (will break the API though).
- The list associations operation on the HubSpot API doesn't return full entities, only a list of ID's, so deserialization of this fails.

**Comment by roycornelissen** [comment]
Hm, I see now that the serialization error I had was caused by confusion about the API. I will submit a (breaking) PR to prevent that confusion.

**Comment by nover** [comment]
All good, thanks 👍  I'll make sure to tag the upcoming release as breaking
