### ISSUE TITLE
Adding contact to company

### ISSUE THREAD

**Issue by andyjonesx** [skarpdev/dotnetcore-hubspot-client#59]
Hi. Is it possible to link a contact to a company using this wrapper?

**Comment by nover** [comment]
The association API available since `v0.14.0` should handle this - if not let me know.

**Comment by roycornelissen** [comment]
@andyjonesx There is also another way: if you expose the `associatedcompanyid` property on your contact entity, you can set that. This is how I did it:

```csharp
[DataContract]
public class CustomContactHubSpotEntity: ContactHubSpotEntity
{
    // ... some custom properties we added
    [DataMember(Name = "hubspot_owner_id")]
    public string OwnerId { get; set; }
    [DataMember(Name = "associatedcompanyid")]
    public string AssociatedCompanyId { get; set; }
}
```

Then you can just do this:

```csharp
var newContact = new CustomContactHubSpotEntity
{
    Email = email,
    Lastname = name,
    Phone = phone,
    OwnerId = hubSpotOwnerId,
    AssociatedCompanyId = hubSpotCompanyId
};

await contactClient.CreateAsync<CustomContactHubSpotEntity>(newContact).ConfigureAwait(false);
```

**Comment by andyjonesx** [comment]
Great thanks. I got it working with the association, but that's an interesting way too @roycornelissen .

Here's what I did:

`
AssociationHubSpotEntity association = new AssociationHubSpotEntity
            {
                FromObjectId = contactId,
                ToObjectId = companyId,
                DefinitionId = 1 // contact to company
            };
            await _associationsClient.Create(association);
`
