### ISSUE TITLE
Get list of all contact lists

### ISSUE THREAD

**Issue by davymirfin** [skarpdev/dotnetcore-hubspot-client#62]
Does the wrapper support "Get all contact lists" (https://legacydocs.hubspot.com/docs/methods/lists/get_lists) please? If so how should it be called please?

**Comment by nover** [comment]
hi @davymirfin 

I'm pretty sure the `HubSpotContactClient.ListAsync` covers your needs. 

Take a look at the readme - it has a short example of how to use the contact client:
https://github.com/skarpdev/dotnetcore-hubspot-client#contact

Hope this covers your question :)

**Comment by davymirfin** [comment]
hi @nover,

Many thanks for getting back to me so quickly.

My problem is that I need a list that contains all the possible list name values along with their corresponding listId. The HubSpotContactClient.ListAsync returns lists of contacts and I am able to use that and I understand how to add new custom properties (your documentation is very clear) but I need a list of ContactListHubSpotEntity rather than a list of ContactHubSpotEntity - i.e. in this case I am not interested in the contact data contained in the ContactList but in the properties that apply to the ContactList itself.

The path I need to access is:

   /contacts/v1/lists (see https://legacydocs.hubspot.com/docs/methods/lists/get_lists )

But via HubSpotContactClient I seem to only be able to access:

   /contacts/v1/lists/all/contacts/all


So it looks to me that I need to use the API:

   Skarp.HubSpotClient.ListOfContacts.HubSpotListOfContactsClient

rather than

   Skarp.HubSpotClient.Contact.HubSpotContactClient

However, HubSpotListOfContactClient.ListAsync does not exist and there is only this:

   public System.Threading.Tasks.Task<T> GetListByIdAsync<T>(long listId, [Skarp.HubSpotClient.ListOfContacts.ListOfContactsRequestOptions opts = null])
    Member of Skarp.HubSpotClient.ListOfContacts.HubSpotListOfContactsClient

which requires that the caller already knows the listid.

That is my key problem - I don't know what listid values are available.

Do I need to implement the call myself?

Many Thanks for your help.

**Comment by nover** [comment]
@davymirfin 

Aha I see, thanks for your explanation. So the `list of lists` is what you need :)
That is correct, it's not currently in the client, and I would also argue that it could live perfectly fine in the  `HubSpotContactClient` or a new `ContactList` client can be added as you hint at.

If the response format is not very different in that call it should be fairly trivial to add support for it if you want to give it a shot(I will happily take your MR). If you don't have time or are not sure what to do, I can have a look some time this week. Or perhaps we're in luck and @roycornelissen will have some spare time to contribute like he has in the past.

Let me know.

**Comment by davymirfin** [comment]
hi @nover,
I've done lots of REST API client calls in C# before (not for HubSpot) but it looks like you have a very neat style and I'll have to study it a bit to make sure I know what I am doing. That said it would be nice to contribute if I can - if I do it and my contribution is not good enough for you I will not be upset to have it improved. I certainly value your wrapper - it seems to work well for the methods I have used and it is great that it is current and well used.

**Comment by nover** [comment]
Thank you @davymirfin - I will never be upset about contributions to the things I maintain in the open - if contributions require improvements we take it in a good tone and work together to get it fixed up, so please don't hesitate to submit your code.

There should be plenty examples and tests in the code for you to look at to get the general idea of how it works and how I like the code to be submitted 😊

**Comment by davymirfin** [comment]
Hi @nover 
I managed to add the functionality I need. I have tested it with a test application against my own HubSpot portal. I have created a fork and my 4 changes are now in there. i.e. They implement the new Get list of contact lists. I am new to this so please forgive my ignorance. Do you want me to create a pull request?

**Comment by nover** [comment]
Great @davymirfin - please create a pull request here so it can be reviewed and merged.

**Comment by davymirfin** [comment]
Done that @nover. Please let me know if I have neglected something. I could have included code snippet documentation showing how to call it.

**Comment by SeanTarrant** [comment]
Hi @nover @davymirfin,

I'm also struggling to get a list of lists and have been trying to use your HubSpotListOfContactsClient but having no success. 

I'm current using the below to get lists but this isn't returning anything, am I using the correct class?
`_lists.GetListAsync<ListOfContactListsHubSpotEntity>()`

Is it possible to provide an example or getting a list of lists?
