### ISSUE TITLE
.Net Framework support

### ISSUE THREAD

**Issue by sheam** [skarpdev/dotnetcore-hubspot-client#71]
I know description states that this is a .Net-Core project, however this Nuget package states that this is a Net Standard 2.0 project. But if I use it will a .Net Framework project get a loader issue with (SimpleInjector) stating that it can't load the assembly that contains Skarp.HubspotClient.

Should this package be usable with .Net Core?

**Comment by nover** [comment]
Hi @sheam - yes this package is tested and compatible with `dotnet core` - I have also previsouly tested with Framework, but it's been a while.

It is targeting `netstandard` to have the broadest compatibility with Framework, core and now "dotnet".
Can you give some more details on your setup so we can fix any bugs?

**Comment by sheam** [comment]
It seems the issue was that that I needed to add the Nugest to the top level assembly, and not just in the wrapper assembly I made. This would have been fine with the Core testing project I made because in Core dependencies are transitive, whereas in Framework they aren't.
