### ISSUE TITLE
Transitive dependency issue when building for Linux

### ISSUE THREAD

**Issue by roycornelissen** [skarpdev/dotnetcore-hubspot-client#83]
As I was updating dependencies in our project (including this HubSpot library), I noticed that there's an issue with a transitive dependency (via `RapidCore`). The situation is that we are running this in a .NET 6.0 application on Linux (Docker container). So when we build for the Linux platform, `dotnet restore` fails:

![image](https://user-images.githubusercontent.com/641868/151117189-42384de9-50b0-4b64-ae3c-b7bafcd45bfd.png)

We have "resolved" this by explicitly referencing these assembly versions directly in the application, but I've yet to see whether it holds up at runtime. Unit tests look OK.

I guess it's not really an issue in this library, but rather in `RapidCore` or even `SSH.NET`, something to be aware of.

**Comment by nover** [comment]
@roycornelissen we can look into cleaning that up inside RapidCore.

**Comment by roycornelissen** [comment]
Oh I didn't realize that RapidCore is also yours :). Anyway, I registered an issue there too.
