### ISSUE TITLE
Error in GetByEmailAsync in Company

### ISSUE THREAD

**Issue by MFrattaruolo** [skarpdev/dotnetcore-hubspot-client#85]
Salutations,
I state that I have been using your library with satisfaction for a long time but now I need to search for the Companies with the email
GetByEmailAsync.

Unfortunately I get the following error:

System.ArgumentException: Unable to locate a property on the data class that implements IList <T> where T is a IHubSpotEntity

Unfortunately it is an error that is blocking me and I don't know how to go on.
I would be very grateful if you could point me to a quick fix ... or have you planned to release a fix.

I thank you

**Comment by LeeStevens318** [comment]
Hi @MFrattaruolo,

Can you please post your code where you are using `GetByEmailAsync<T>` and the `T` class your using?

**Comment by MFrattaruolo** [comment]
Hi,
first of all, thank you for replying.

I get the error simply by doing this statement:
  var company = await clientCompany.GetByEmailAsync <CompanyHubSpotEntity> (mail);

with
  Skarp.HubSpotClient.Company.Dto.CompanyHubSpotEntity

I hope I answered your questions.
Regards

**Comment by LeeStevens318** [comment]
Hi @MFrattaruolo,

Have you check the Functional Test, there is already a test case for [this](https://github.com/skarpdev/dotnetcore-hubspot-client/blob/2da88db0c3c6a269b067541a83b769224141a71b/test/functional/Company/HubSpotCompanyClientFunctionalTest.cs#L114)

Try
```
var company = await clientCompany.GetByEmailAsync<CompanySearchResultEntity<CompanyHubSpotEntity>>(mail);
```

**Comment by MFrattaruolo** [comment]
Hello,
thank you you were very kind to help me.
By following your advice I was able to solve the problem and continue developing.

Regards
Michele
