### ISSUE TITLE
Private Apps migration

### ISSUE THREAD

**Issue by phillipzada** [skarpdev/dotnetcore-hubspot-client#92]
Hubspot will be updating its authentication mechanism to use Private Apps only in November 2022

![image](https://user-images.githubusercontent.com/12227583/179381774-080104f2-675d-4452-9102-9b4509c67b93.png)

After initial tests, it looks like the library is compatible except for the authentication mechanism. 

Are there any plans to support this change?

**Comment by nover** [comment]
@phillipzada thanks for the heads-up.
Definitely seems like something we'd need to support in this library :)

**Comment by alexcrowdpharm** [comment]
I contributed a related PR to support this upcoming change. #93

**Comment by nover** [comment]
Closed via #96 and released as `0.22.0` but as a non breaking change: https://github.com/skarpdev/dotnetcore-hubspot-client/releases/tag/v0.22.0
