### ISSUE TITLE
Hubspot Auth API changes

### ISSUE THREAD

**Issue by brandonm4** [skarpdev/dotnetcore-hubspot-client#95]
Hi,
We received a notification that the hubspot authentication API was changing - will this library be affected by that or was it already using the newer auth methods?

**Comment by brandonm4** [comment]
Just noticed this a duplicate question / closing

**Comment by nover** [comment]
> Just noticed this a duplicate question / closing

Yeah changes are ongoing to support the new auth mechanism from Hubspot - stay tuned for a release :)
